ALTER TABLE game_states ADD COLUMN IF NOT EXISTS player1_id UUID REFERENCES players(id) ON DELETE SET NULL;
ALTER TABLE game_states ADD COLUMN IF NOT EXISTS player2_id UUID REFERENCES players(id) ON DELETE SET NULL;
ALTER TABLE game_states ADD COLUMN IF NOT EXISTS player1_score INTEGER DEFAULT 0;
ALTER TABLE game_states ADD COLUMN IF NOT EXISTS player2_score INTEGER DEFAULT 0;
ALTER TABLE game_states ADD COLUMN IF NOT EXISTS match_status match_status DEFAULT 'in_progress';
ALTER TABLE game_states ADD COLUMN IF NOT EXISTS last_action_timestamp BIGINT DEFAULT 0;
ALTER TABLE game_states ADD COLUMN IF NOT EXISTS consecutive_passes INTEGER DEFAULT 0;
ALTER TABLE game_states ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE game_states ADD COLUMN IF NOT EXISTS game_mode TEXT DEFAULT 'fives';
ALTER TABLE game_states ADD COLUMN IF NOT EXISTS target_score INTEGER DEFAULT 150;
ALTER TABLE game_states ADD COLUMN IF NOT EXISTS last_player_id UUID REFERENCES players(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_game_states_match_id ON game_states(match_id);
